### ISSUE TITLE
Can not connect any layer to dense layer 

### ISSUE THREAD

**Issue by a0935210570602** [NTUT-kyle/SNNTP#1]
When I design a model, I want to connect the activation layer to the dense layer, however, the right connect part of the dense layer is disabled.

![image](https://github.com/NTUT-kyle/SNNTP/assets/36853870/874e3190-1cc8-4021-a870-542be5abf929)

**Comment by NTUT-kyle** [comment]
At the beginning, my design ended with Dense Layer. It seems that such a design is unnecessary, and I will make adjustments!

**Comment by NTUT-kyle** [comment]
This issue has been resolved in a recent commit, you can check it out!!
